### ISSUE TITLE
Add tests for the CSR matvec method

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#19]
## Description:
Tests whether the matrix-vector product Ax, where A is a sparse matrix under the CSR format, produces an output vector b that is correct in dimension and values.

## Tasks:
- [x] Tests the method will reject invalid arguments, most likely when the matrix and vector dimensions don't match.
- [x] Tests on edge cases, including zero matrices, identity matrices, etc.
- [x] Tests on a few randomly created sparse matrices and the vectors of the corresponding dimensions. 

## Definition of done:
All tests passed or the appropriate error is handled.

**Comment by rsshast** [comment]
I am reviewing this task!

**Comment by amirnzm** [comment]
I am reviewing this.

**Comment by dbloc-umich** [comment]
@amirnzm this is ready for review.

**Comment by amirnzm** [comment]
The issue description, tasks, and definition of done make sense to me and is good to go.
