### ISSUE TITLE
Add a DEN matrix class

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#2]
## Description:
Defines a DEN matrix class that includes a class constructor, destructor, and declares variable types. This is a subclass of SparseMatrix. Declaration of this class also includes declaration of child functions, such as dense matrix-vector multiply.

## Tasks:
- [] Determine what #include preprocessor directives are required
- [] Communicate with others to determine: namespace name, class name, input arguments, potential outputs
- [] Incorporate constructor of default and overloaded types, and deconstructor calls
- [] Determine names of required functions such as assebmleMat(), Matvev(), disassembleMat(), etc.
- [] Incorporate assembly and diassembly calls that takes data from parent class and constructs dense matrix

## Definition of done:
Pass all the unit tests for declaring and calling class. Implement reviewers comments
Must include a default constructor and a constructor which takes one argument per member variable and directly assembles the class. Ensure all blocking issues are resolved before considering this task done. Issues that block the completion of this task is the creation of the SparseMatrix class.

**Comment by AndrewPanter** [comment]
Issue description ready for review.

**Comment by ffarha** [comment]
I'm reviewing this.

**Comment by AndrewPanter** [comment]
Implementation ready for testing

**Comment by ffarha** [comment]
@DecBrick could you confirm if the unit tests passed for the accessor methods?

**Comment by ffarha** [comment]
The implementation looks good to me, with mostly all tasks checked and proper documentation added. I built and made it on my DEN branch, and it ran without any issues. However, not sure whether the tests for this have been merged with this branch, could not find them there.
