### ISSUE TITLE
Storage tests for ELL

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#53]
## Description:

As defined in Lab 6 and Lec13 notes, the assembleStorage() method deals with converting the sparse matrix representation from the standard input to the format required (which is presently ELL). This issue deals with implementing and running unit tests to ensure:

- **The data from the _buildCoeff is being read correctly**: this requires information on what sparse matrix format is being passed as input, and if all the required data arrays for that format are being read correctly. The common attributes such as number of rows, number of columns and number of non-zero elements should not vary between input format and ELL.
- **The output arrays are consistent with the ELL format**: As already known, the ELL sparse matrix format is represented by the _colIdx_ and _values_ arrays. The unit tests should ensure that the storage method returns these two arrays and that they are of the right size and data type
-  **The data from the input arrays is correctly mapped to the output arrays**
-  **The padding is being handled correctly**: The padding needs to be present at the correct elements in the _colIdx_ and the values for those elements need to be disregarded. Prior information on how the padding is implemented in _colIdx_ is required. Extra caution needs to be taken that elements are not padded incorrectly which could lead to incorrect matvec results.
-  **Extra consideration for different matrix formats that result in revised arrays**:  Just as in HW2 where the arrays were different for symmetric matrix case, such cases need to be correctly identified and handled.

This is a non-exhaustive list of requirements, which need to be finalized as one of the tasks. The unit tests will be implemented as _unit_test_ell.cpp_

## Tasks:

- [x] **Identify the requirements that the unit tests should test for**: This includes the requirements mentioned in the Description (mentioned below), but is by no means an exhaustive list: 

1. assembleStorage() changes the state of the matrix from 'building' to 'assembled'
2. The output arrays of assembleStorge() are consistent with the ELL format
3. The input data from_buildCoeff is correctly mapped to the output arrays of assembleStorge()
4. The padding is being handled correctly for the ELL format: **the padded elements should have colIdx = ncol+1 and val = 0**
6. disassembleStorage() changes the state of the matrix from 'assembled' to 'building'
7. The storage method can handle both _float_ and _double_ data type

- [x] **Identify the edge cases for which unit tests should be implemented**: This includes, but isn't restricted to:

1. Zero Matrix : assembleStorage() should return empty pointer
2. Only one element filled in otherwise zero matrix : assembleStorage() arrays should have all elements padded EXCEPT the one filled
3. Empty row: elements corresponding to that row should be padded
4. Dense Matrix: should not have any padding
5. Multi-diagonal matrix with bands of 0 between the diagonals: should return the correct padding

- [x] **Implementing the unit test for each of the requirements/edge cases**: This includes:

1. _Identifying the inputs for the unit test_: Unit tests for operations might not require any input (variables to be used would then be defined within local scoped of the test), while unit tests for comparing values of attributes might require more than one input.
8. _Identifying the expected return value of the tests_: Whether the tests is supposed to give a Pass or a Fail to indicate correct implementation

- [x] **Checking if each of the requirements pass the unit tests**: The test should finally be run on the ELL storage methods to check if its implementation is correct

These tasks can be concisely defined and tracked in the lag tables below:

| Requirements |||
|----------------|-|-|
|**Description** | **Unit test implemented? (Y/N)** | **Unit test passed? (Y/N)**|
|assembleStorage() changes the state of the matrix from 'building' to 'assembled' |Y |Y |
|output arrays of assembleStorge() are consistent with the ELL format | Y | Y |
| disassembleStorage() changes the state of the matrix from 'assembled' to 'building'| Y | Y |
| input data from_buildCoeff is correctly mapped to the output arrays of assembleStorge()| Y | Y |
| padding is being handled correctly | Y| Y |
|  can handle both _float_ and _double_ data type| Y | Y |

| Edge Cases |||
|----------------|-|-|
|**Description** | **Unit test implemented? (Y/N)** | **Unit test passed? (Y/N)**|
|Zero Matrix |Y |Y |
|Only one element filled in otherwise zero matrix| Y | Y |
| Empty row| Y | Y|
|Smallest possible Matrix|Y|Y|
|Very Large Matrix|Y|Y|

As soon as the description is added in the tables, the statuses should be changed to N. The status should be respectively changed to Y once the unit test implementation is done successfully, and when the unit test for that requirement/case is passed

- [x] **Communicate status of unit test passing to the developer**: The end goal of the unit tests is to ensure that the Storage methods are implemented correctly. This requires communication with the methods developer about the status of the unit tests passing

## Definition of done:
The task is considered done when:

1. _All requirements/edge cases are identified and logged into the tables above_
7. _All the unit tests are implemented_: The status column for implementation in both tables shall be Y
9. _The status of the unit tests passing should be correctly reflected and communicated_: Ideally, this shall lead to the status column for the passing in both tables to be Y. Realistically, some unit tests might not pass in the first go. Those should be indicated correctly so that the Storage methods developer can address them. A comment tagging the methods developer should be included to convey the results

**Comment by MoonBH-UoM** [comment]
@swame2000 I believe you have to review this issue, which I have updated. Kindly review the same. Thank you.

**Comment by swame2000** [comment]
@MoonBH-UoM I have reviewed your description, task definitions and definition of done. Please clarify why action 2 under task 1 mentions "other specified formats". The understanding is for the ELL implementation, the output arrays should ONLY be consistent with the ELL format. All other details look consistent and thorough, no other clarifications are sought at this time. Thank you.

**Comment by MoonBH-UoM** [comment]
@swame2000 Thanks for pointing that out. That point has been added for testing disassembleStorage() methods. This requirement needs to be clarified in Piazza/during lecture, and will be accordingly updated.

**Comment by swame2000** [comment]
Noted with thanks.

**Comment by xianyu2023umich** [comment]
Hi I'm the one who opened up ELL branch. I just noticed you copied the ELL and opened up a new one for this issue. I'm not very sure about this but JDS branch contains everyone's work so I suppose that's the way of doing it.

**Comment by MoonBH-UoM** [comment]
Hi @xianyu2023umich . I'm unsure whether we are supposed to have a branch for each issue. I merged the branch for this issue with the ELL branch so it should be up to date with it (I have done the same for JDS accessors as well). Further clarification in class would be required.

**Comment by MoonBH-UoM** [comment]
@swame2000 the branch is ready for review.
Passing of the unit tests is blocked by #28 and #48

**Comment by bkochuna** [comment]
@MoonBH-UoM I think the [`ELL-assemblage`](https://github.com/bkochuna/ners570f24-SpMV/tree/ELL-assemblage) branch is ready for the test. I tried running the test, but I get a failed assertion in the test at line 170.
```
TEST((banded_nxn_mdiag_deld<10,0,0, T>));
```
It fails because in the test the assertion requires the second argument (`0`) be `>0`.

**Comment by MoonBH-UoM** [comment]
@bkochuna I have rectified the error and pushed the edited storage file to ELL branch. Kindly use the modified file.

**Comment by swame2000** [comment]
@MoonBH-UoM I have reviewed the unit test framework implemented for testing ELL storage. The tests are comprehensive and the code is very readable and clearly commented. No obvious errors were noticed except a minor inconsistency. Is it not necessary to assert the state of the matrix in each of the different test cases before assembly, after assembly, before disassembling and after disassembling, just to be thorough? Thanks.

**Comment by MoonBH-UoM** [comment]
@swame2000 The test case _matrix_state_test_ checks the matrix state before and after assembleStorage() and disassembleStorage(). This is done to avoid repeated code in all tests (since the change in states will be same throughout all other cases)

**Comment by swame2000** [comment]
@MoonBH-UoM Noted with thanks.

**Comment by MoonBH-UoM** [comment]
@bkochuna , I have updated the issue basis the communication regarding passing of the unit tests. This satisfies the Definition of Done. @swame2000 I am considering your review as approval of the implementation. With this, I am closing the issue.
