### ISSUE TITLE
Add construction/destruction tests for the COO matrix class

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#8]
## Description:
This goal of this issue is to implement unit tests to evaluate the functionality of constructor and destructor methods for the COO class. Constructors serve the role of making an instance of a class, often given user input. They should parse that input and create an object with key variables set. For the COO class, the inputs would be the matrix dimensions and the precision for the matrix's data. The unit tests should verify this functionality. Destructors serve to remove an instance of an object from memory and are important to avoid memory leaks. The unit tests should verify that the object is removed from memory.

## Tasks:
- [x] Discuss with others how precision will be implemented, at the template level, or as an input to the constructor. This task blocks the completion of all the following tasks.
- [x] Discuss with others what data types will be used for indices
- [x] Write a unit test checking that the constructor successfully made an object
- [x] Write unit tests checking that all inputs to the matrix constructor are correctly set in the object that is created. Write a unit test giving a sample input and checking that the following are correct in the new object:
1. Number of rows
2. Number of columns
3. Data type of the matrix's values
4. Data type of indices (I,J vectors)
- [ ] Write a unit test creating a COO matrix and checking that the matrix is no longer in memory after the destructor has been called

## Definition of done:
Unit tests are written to evaluate: whether the constructor makes an object, whether input data to the constructor is correctly reflected in the created object, and whether the destructor removes the object from memory.

**Comment by athenafhl** [comment]
I'm reviewing this.

**Comment by athenafhl** [comment]
Everything is good! You may also want to check if the values are non-zero.

**Comment by bjorngkierulf** [comment]
I'm not sure I understand - which values should I check are non-zero?

**Comment by athenafhl** [comment]
> I'm not sure I understand - which values should I check are non-zero?

Nevermind. I was thinking about the storage test. Sorry about that!

**Comment by bjorngkierulf** [comment]
@athenafhl this is ready for review. I decided not to do a test checking that the object is removed from memory, because I couldn't find a clean way to do that, and I think it is enough to verify that the code calls the destructor without error.

**Comment by athenafhl** [comment]
> @athenafhl this is ready for review. I decided not to do a test checking that the object is removed from memory, because I couldn't find a clean way to do that, and I think it is enough to verify that the code calls the destructor without error.

Sure. I added a comment to your PR.

**Comment by bjorngkierulf** [comment]
Great! I'll finish that pull request and close this issue.
